{
  description = "Max's Dotfiles";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, home-manager, ... }@inputs:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
        config.nvidia.acceptLicense = true;
      };

      # Helper function to create home configurations (for standalone use on non-NixOS)
      mkHome = { extraModules ? [] }:
        home-manager.lib.homeManagerConfiguration {
          inherit pkgs;
          extraSpecialArgs = { inherit inputs; };
          modules = [ ./home.nix ] ++ extraModules;
        };

      # Helper function to create NixOS system configurations
      mkNixOS = { hostname, extraModules ? [], homeModules ? [] }:
        nixpkgs.lib.nixosSystem {
          inherit system;
          specialArgs = { inherit inputs; };
          modules = [
            ./nixos/configuration.nix
            { networking.hostName = hostname; }
            home-manager.nixosModules.home-manager
            {
              home-manager.useGlobalPkgs = true;
              home-manager.useUserPackages = true;
              home-manager.extraSpecialArgs = { inherit inputs; };
              home-manager.users.max = {
                imports = [ ./home-nixos.nix ] ++ homeModules;
              };
            }
          ] ++ extraModules;
        };
    in
    {
      # ============================================
      # Standalone Home Manager (for Debian, etc.)
      # Usage: home-manager switch --flake .#desktop
      # ============================================
      homeConfigurations = {
        # Desktop with NVIDIA GPU and GUI apps
        "desktop" = mkHome {
          extraModules = [ ./hosts/desktop.nix ];
        };

        # Server without GPU or GUI apps
        "server" = mkHome {
          extraModules = [ ./hosts/server.nix ];
        };
        
        # Legacy alias
        "max" = mkHome {
          extraModules = [ ./hosts/desktop.nix ];
        };
      };

      # ============================================
      # NixOS System Configurations
      # ============================================
      nixosConfigurations = {
        # VM for testing (no NVIDIA, use virtual graphics)
        # Usage: nixos-rebuild build-vm --flake .#desktop-vm
        #        ./result/bin/run-nixos-desktop-vm
        "desktop-vm" = mkNixOS {
          hostname = "nixos-desktop";
          extraModules = [ ./nixos/hardware-vm.nix ];
        };

        # Real desktop with NVIDIA (for spare SSD install)
        # Usage: sudo nixos-rebuild switch --flake .#desktop-nixos
        "desktop-nixos" = mkNixOS {
          hostname = "nixos-desktop";
          extraModules = [
            ./nixos/hardware-nvidia.nix
            # On real install, also add:
            # ./nixos/hardware-configuration.nix  # Generated by nixos-generate-config
          ];
        };
      };
    };
}
