---
- name: Setup Development Environment
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    dotfiles_dir: "{{ playbook_dir }}"
    nvm_version: "0.40.1"
    node_version: "23"
    required_packages:
      - git
      - zsh
      - stow
      - curl
      - neovim

  handlers:
    - name: Reload zsh config
      ansible.builtin.debug:
        msg: "Zsh configuration updated. Please restart your shell or run 'source ~/.zshrc' for changes to take effect."
      listen: "Reload zsh config"
    - name: Reload tmux config
      ansible.builtin.shell: |
        if pgrep tmux > /dev/null; then
          tmux source-file {{ lookup('env', 'HOME') }}/.tmux.conf
        fi
      args:
        executable: /bin/bash
      changed_when: false
      failed_when: false

  pre_tasks:
    - name: Update apt cache and upgrade all packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: dist
      changed_when: false
      tags: [system_setup]

    - name: Install all required system packages
      become: true
      ansible.builtin.apt:
        name: "{{ required_packages }}"
        state: present
      when: required_packages | length > 0
      tags: [system_setup]

  tasks:
    - name: Run Git setup tasks
      ansible.builtin.include_tasks: tasks/git.yml
      tags: [git, tools]

    - name: Run Zsh setup tasks
      ansible.builtin.include_tasks: tasks/zsh.yml
      tags: [zsh, tools]

    - name: Run Tmux setup tasks
      ansible.builtin.include_tasks: tasks/tmux.yml
      tags: [tmux, tools]

    - name: Run Node.js setup tasks
      ansible.builtin.include_tasks: tasks/node.yml
      tags: [node, tools]

    - name: Run Python/uv setup tasks
      ansible.builtin.include_tasks: tasks/python_uv.yml
      tags: [python, uv, tools]

    - name: Run Neovim setup tasks
      ansible.builtin.include_tasks: tasks/neovim.yml
      tags: [neovim, tools]

    - name: Run GitHub setup tasks
      ansible.builtin.include_tasks: tasks/github.yml
      tags: [github, tools]

    - name: Setup local bin directory and scripts
      ansible.builtin.include_tasks: tasks/local_bin.yml
      tags: [local_bin, tools]

    - name: Display completion status
      ansible.builtin.debug:
        msg: "All development tools have been installed and configured"
