---
- name: Setup Development Environment
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    dotfiles_dir: "{{ lookup('env', 'HOME') }}/dotfiles/config"
    required_packages: []

  pre_tasks:
    - name: Collect required system packages
      ansible.builtin.set_fact:
        required_packages: "{{ required_packages | union(lookup('file', item).splitlines()) }}"
      loop: "{{ role_files }}"

    - name: Update apt cache and upgrade all packages
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist

    - name: Install all system packages at once
      become: true
      ansible.builtin.apt:
        name: "{{ required_packages }}"
        state: present
        update_cache: yes
      when: required_packages | length > 0

  handlers:
    - name: Include Handlers
      ansible.builtin.include_tasks: handlers/main.yml

  tasks:
    - name: Run development tools setup
      ansible.builtin.include_tasks:
        file: "{{ item }}"
      loop: "{{ role_files }}"
      when: not playbook_dir == ansible_env.HOME ~ '/.dotfiles'

    - name: Verify dotfiles location
      ansible.builtin.debug:
        msg: "Dotfiles are located correctly at {{ playbook_dir }}"
      when: playbook_dir == ansible_env.HOME ~ '/.dotfiles'

    - name: Display completion status
      ansible.builtin.debug:
        msg: "All development tools have been installed and configured"
