---
- name: Setup Development Environment
  hosts: localhost
  connection: local
  gather_facts: true
  gather_subset: ['!all', 'min']
  vars:
    dotfiles_dir: "{{ playbook_dir }}"
    required_packages:
      - git
      - zsh
      - stow
      - curl
      - neovim

  pre_tasks:
    - name: Update apt cache and upgrade all packages
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist

    - name: Install all required system packages
      become: true
      ansible.builtin.apt:
        name: "{{ required_packages }}"
        state: present
        update_cache: yes
      when: required_packages | length > 0

  tasks:
    - name: Run Git setup tasks
      ansible.builtin.include_tasks: tasks/git.yml
      tags: [git, tools]

    - name: Run Zsh setup tasks
      ansible.builtin.include_tasks: tasks/zsh.yml
      tags: [zsh, tools]

    - name: Run Tmux setup tasks
      ansible.builtin.include_tasks: tasks/tmux.yml
      tags: [tmux, tools]

    - name: Run Node.js setup tasks
      ansible.builtin.include_tasks: tasks/node.yml
      tags: [node, tools]

    - name: Run Python/uv setup tasks
      ansible.builtin.include_tasks: tasks/python_uv.yml
      tags: [python, uv, tools]

    - name: Run Neovim setup tasks
      ansible.builtin.include_tasks: tasks/neovim.yml
      tags: [neovim, tools]

    - name: Run GitHub setup tasks
      ansible.builtin.include_tasks: tasks/github.yml
      tags: [github, tools]

    - name: Display completion status
      ansible.builtin.debug:
        msg: "All development tools have been installed and configured"
