---
- name: Create Git configuration
  ansible.builtin.copy:
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    content: |
      [init]
        defaultBranch = main

      [user]
        name = Maximilian Noller
        email = max.noller1@gmail.com

      [includeIf "hasconfig:remote.*.url:gitlab.ub.uni-bielefeld.de*/**"]
        path = ~/.gitconfig-work
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0600"

- name: Create work Git config
  ansible.builtin.copy:
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig-work"
    content: |
      [user]
        email = maximilian.noller@uni-bielefeld.de
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0600"

- name: Create projects directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/projects"
    state: directory
    mode: "0755"
