---
- name: Check if GitHub CLI is installed
  ansible.builtin.command: gh --version
  register: gh_check
  ignore_errors: true
  changed_when: false

- name: Install GitHub CLI
  become: true
  ansible.builtin.apt:
    name: gh
    state: present
  when: gh_check.rc != 0

- name: Display GitHub CLI version
  ansible.builtin.debug:
    msg: "GitHub CLI installed: {{ gh_check.stdout_lines[0] | default('newly installed') }}"

- name: Check if gh-act extension is installed
  ansible.builtin.command: gh extension list
  register: gh_extension_list
  changed_when: false
  failed_when: false # Don't fail if gh isn't installed yet or extensions cause errors

- name: Install gh-act extension (for local GitHub Actions testing)
  ansible.builtin.command:
    cmd: gh extension install nektos/gh-act
  environment:
    GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"
  when: "'nektos/gh-act' not in gh_extension_list.stdout"
  tags:
    - github
    - tools
