---
- name: Add Neovim unstable PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
    update_cache: true

- name: Deploy Neovim configuration using GNU Stow
  ansible.builtin.command:
    cmd: stow -t "{{ lookup('env', 'HOME') }}" nvim
    chdir: "{{ dotfiles_dir }}"
  register: stow_nvim
  changed_when: "'LINK:' in stow_nvim.stdout"
  tags:
    - neovim
    - tools
