---
- name: Check if nvm is installed
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh"
  register: nvm_check

- name: Install nvm (Node Version Manager)
  ansible.builtin.shell: |
    set -o pipefail && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    executable: /bin/bash
  when: not nvm_check.stat.exists
  register: nvm_installed
  changed_when: not nvm_check.stat.exists

- name: Check if Node.js 23 is installed
  ansible.builtin.shell: ". $HOME/.nvm/nvm.sh && nvm list 23"
  register: node_check
  ignore_errors: true
  changed_when: false

- name: Install Node.js 23 using NVM
  ansible.builtin.shell: ". $HOME/.nvm/nvm.sh && nvm install 23"
  args:
    executable: /bin/bash
  when: node_check.rc != 0
  register: node_installed
  changed_when: node_check.rc != 0

- name: Verify Node.js installation
  ansible.builtin.shell: ". $HOME/.nvm/nvm.sh && node -v"
  args:
    executable: /bin/bash
  register: node_version
  changed_when: false

- name: Verify npm installation
  ansible.builtin.shell: ". $HOME/.nvm/nvm.sh && npm -v"
  args:
    executable: /bin/bash
  register: npm_version
  changed_when: false

- name: Display installed Node.js and NPM versions
  ansible.builtin.debug:
    msg: |
      Node.js Version: {{ node_version.stdout }}
      NPM Version: {{ npm_version.stdout }}
  tags:
    - node
    - tools

- name: Ensure .zshrc sources NVM
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    create: yes # Create the file if it doesn't exist
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0644"
    marker: "# {mark} ANSIBLE MANAGED BLOCK NVM"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  when: nvm_check.stat.exists or nvm_installed.changed # Only run if NVM is installed or was just installed
