---
- name: Check if nvm is installed
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh"
  register: nvm_check

- name: Install nvm (Node Version Manager)
  ansible.builtin.shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    executable: /bin/bash
  when: not nvm_check.stat.exists
  register: nvm_installed
  changed_when: not nvm_check.stat.exists

- name: Ensure NVM is sourced in the current shell
  ansible.builtin.shell: 'source $HOME/.nvm/nvm.sh && echo "nvm loaded"'
  args:
    executable: /bin/bash
  when: nvm_installed.changed

- name: Check if Node.js 23 is installed
  ansible.builtin.shell: ". $HOME/.nvm/nvm.sh && nvm list 23"
  register: node_check
  ignore_errors: yes
  changed_when: false

- name: Install Node.js 23 using NVM
  ansible.builtin.shell: ". $HOME/.nvm/nvm.sh && nvm install 23"
  args:
    executable: /bin/bash
  when: node_check.rc != 0
  register: node_installed
  changed_when: node_check.rc != 0

- name: Verify Node.js installation
  ansible.builtin.shell: ". $HOME/.nvm/nvm.sh && node -v"
  args:
    executable: /bin/bash
  register: node_version
  changed_when: false

- name: Verify npm installation
  ansible.builtin.shell: ". $HOME/.nvm/nvm.sh && npm -v"
  args:
    executable: /bin/bash
  register: npm_version
  changed_when: false

- name: Display installed Node.js and NPM versions
  ansible.builtin.debug:
    msg: |
      Node.js Version: {{ node_version.stdout }}
      NPM Version: {{ npm_version.stdout }}
