---
- name: Check if uv is installed
  ansible.builtin.shell: "command -v uv"
  register: uv_check
  ignore_errors: true
  changed_when: false

- name: Install uv Python package manager using standalone installer
  ansible.builtin.shell: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    executable: /bin/bash
  when: uv_check.rc != 0
  register: uv_install
  changed_when: uv_install.rc == 0

- name: Update uv if it is already installed
  ansible.builtin.shell: "uv self update"
  when: uv_check.rc == 0
  register: uv_update
  changed_when: uv_update.rc == 0
