---
# Removed the initial command check

- name: Install uv Python package manager using standalone installer
  ansible.builtin.shell: |
    set -o pipefail && curl -LsSf https://astral.sh/uv/install.sh | sh  # noqa command-instead-of-shell
  args:
    executable: /bin/bash
    # This task is skipped if the target file already exists
    creates: "{{ ansible_env.HOME }}/.uv/bin/uv"
  register: uv_install
  # Consider changed only when the script actually ran (implies creates file didn't exist)
  changed_when: uv_install.rc == 0
