---
# Use stat to check for the binary's existence in the expected install location
- name: Check if uv is installed
  ansible.builtin.command: uv --version
  register: uv_check
  ignore_errors: true
  changed_when: false

- name: Install uv Python package manager using standalone installer
  ansible.builtin.shell: |
    set -o pipefail && curl -LsSf https://astral.sh/uv/install.sh | sh  # noqa command-instead-of-shell
  args:
    executable: /bin/bash
  when: uv_check.rc != 0
  register: uv_install
  changed_when: uv_install.rc == 0

- name: Update uv if it is already installed
  ansible.builtin.command: uv self update
  when: uv_check.rc == 0
  register: uv_update
  changed_when: "'Updated uv to' in uv_update.stdout"
  tags:
    - python
    - uv
