---
- name: Clone TPM (Tmux Plugin Manager) repository
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    version: master
    force: yes
    update: yes

- name: Check state of .tmux.conf before stowing
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.tmux.conf"
  register: tmux_conf_link_status

- name: Deploy tmux configuration using GNU Stow
  ansible.builtin.command:
    cmd: stow -t "{{ lookup('env', 'HOME') }}" tmux
    chdir: "{{ dotfiles_dir }}/config"
  register: stow_tmux
  changed_when: >
    not tmux_conf_link_status.stat.exists or
    not tmux_conf_link_status.stat.islnk or
    tmux_conf_link_status.stat.lnk_source != dotfiles_dir + '/config/tmux/.tmux.conf'
  notify: Reload tmux config
