---
- name: Clone TPM (Tmux Plugin Manager) repository
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    version: master
    force: yes
    update: yes

- name: Deploy tmux configuration using GNU Stow
  ansible.builtin.command:
    cmd: stow -t "{{ lookup('env', 'HOME') }}" tmux
    chdir: "{{ dotfiles_dir }}/config"
  register: stow_tmux
  # NOTE: changed_when relies on stow's stdout. A more robust check
  # could involve using stat on a key symlink (e.g., ~/.tmux.conf).
  changed_when: "'LINK:' in stow_tmux.stdout"

- name: Reload tmux configuration if tmux is running
  ansible.builtin.shell: |
    if pgrep tmux > /dev/null; then
      tmux source-file {{ lookup('env', 'HOME') }}/.tmux.conf
    fi
  args:
    executable: /bin/bash
  register: tmux_running
  changed_when: false
  failed_when: false
