---
- name: Install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_zsh_check

- name: Install Oh My Zsh
  ansible.builtin.shell: |
    set -o pipefail && curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  args:
    executable: /bin/bash
  when: not oh_my_zsh_check.stat.exists
  register: oh_my_zsh_installed
  changed_when: not oh_my_zsh_check.stat.exists

- name: Deploy ZSH configuration using GNU Stow
  ansible.builtin.command:
    cmd: stow -t "{{ lookup('env', 'HOME') }}" zsh
    chdir: "{{ dotfiles_dir }}"
  register: stow_zsh
  changed_when: "'LINK:' in stow_zsh.stdout"

- name: Set ZSH as default shell
  become: true
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
