# VM Hardware Configuration
# This file is used for VM testing only.
# On a real install, replace this import with hardware-configuration.nix
# generated by: nixos-generate-config

{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # VM-specific settings
  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];
  boot.kernelModules = [
    "kvm-intel"
    "kvm-amd"
  ];

  # Filesystems for VM
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  # Use virtual graphics in VM (no NVIDIA)
  # Real hardware will use hardware-nvidia.nix instead
  services.xserver.videoDrivers = [ "modesetting" ];

  # VM optimizations
  virtualisation.vmVariant = {
    virtualisation = {
      memorySize = 4096; # MB
      cores = 4;
      resolution = {
        x = 1920;
        y = 1080;
      };
      qemu.options = [
        "-enable-kvm"
        "-vga virtio"
      ];
    };
  };
}
