name: Ansible Lint

on:
  push:
    branches: [ main ]
    paths:
      - '**.yml'
      - '**.yaml'
      - 'requirements-dev.txt'
  pull_request:
    branches: [ main ]
    paths:
      - '**.yml'
      - '**.yaml'
      - 'requirements-dev.txt'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv and cache dependencies
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.20"
          enable-cache: true
          cache-dependency-glob: "requirements-dev.txt"

      - name: Check uv version and path
        run: |
          which uv
          uv --version

      - name: Install dependencies with uv pip
        run: uv pip install --system -r requirements-dev.txt

      - name: Run ansible-lint
        run: |
          uv run ansible-lint

      - name: Run yamllint
        run: |
          uv run yamllint .
