name: Ansible Lint

on:
  push:
    branches: [main]
    paths:
      - "site.yml"
      - "tasks/**"
  pull_request:
    branches: [main]
    paths:
      - "site.yml"
      - "tasks/**"

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv and cache dependencies
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.4.20"
          enable-cache: true
          cache-dependency-glob: "requirements-dev.txt"

      - name: Check uv version and path
        run: |
          which uv
          uv --version

      - name: Install dependencies with uv pip
        run: |
          uv pip install --system ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint
